### ISSUE TITLE
Link click on TOC breaks highlighting when scrolling

### ISSUE THREAD

**Issue by hirusepalika** [tscanlin/tocbot#376]
Hello!

We are running into an issue with table of contents after updating to 4.33.0.

**Current behavior**
1. Click on a link in the table of contents.
2. Scroll past it up or down, the highlight is fixed on the one link I clicked.

**Expected behavior**
1. Click on a link in the table of contents.
2. Scroll past it up or down, the highlight should change based on what anchor is in view.

I narrowed the issue down to the following
- Version: [v4.32.3-0](https://github.com/tscanlin/tocbot/releases/tag/v4.32.3-0)
- Commit: https://github.com/tscanlin/tocbot/commit/b5b25013dfcce37621e6f930660f1b9e70df5c42

I am using yarn -> `yarn add tocbot@https://github.com/tscanlin/tocbot#b5b25013dfcce37621e6f930660f1b9e70df5c42`

Using Javascript to initialize tocbot,

```
tocbot.init({
    tocSelector: ".js-toc",
    positionFixedSelector: ".js-toc",
    contentSelector: ".docs-content",
    headingSelector: "h2, h3, h4",
    collapseDepth: 6, // Uncollapse all headers.
    // These should match our header-offset CSS variable.
    // header-offset = 4rem = 64px
    headingsOffset: 64,
    scrollSmoothOffset: -64,
  });
```

**Comment by tscanlin** [comment]
Hmm, I don't think I'm seeing this on: https://tscanlin.github.io/tocbot/#options

Do you have a link you can share where this is happening?

**Comment by hirusepalika** [comment]
> Hmm, I don't think I'm seeing this on: https://tscanlin.github.io/tocbot/#options
> 
> Do you have a link you can share where this is happening? Also are there any console errors?

This is our doc website where we use TOC.
https://docs.gitlab.com/user/project/repository/code_suggestions/

If you just scroll, it works great. But if you click a header and scroll,  the highlighting no longer moves with scroll.

**Comment by tscanlin** [comment]
Oh I see, you are using an old version. Can you try the latest version and see if you still notice an issue? 
[4.35.0](https://github.com/tscanlin/tocbot/releases/tag/v4.35.0)

This was fixed in this [issue](https://github.com/tscanlin/tocbot/issues/372).

Hope that helps!

**Comment by hirusepalika** [comment]
> Oh I see, you are using an old version. Can you try the latest version and see if you still notice an issue? [4.35.0](https://github.com/tscanlin/tocbot/releases/tag/v4.35.0)
> 
> This was fixed in this [issue](https://github.com/tscanlin/tocbot/issues/372).
> 
> Hope that helps!

HI @tscanlin, I tried updating to 4.35.0 and it slightly improved?
But still not the expected.
The scroll highlight only works for the selected link and when I scroll all the way to the top 

https://github.com/user-attachments/assets/2813abfb-c59b-4e72-bb8f-be47561e3e92


Not sure if this matters.
The body content is in a separate div from where TOC is.

Content is setup like the following,

```
<div class="main-content">
    <div class="content">
    {/* this is where content is rendered */}
   </div>
</div>
```

the toc is rendered after this
```
<aside ...>
    <div class="js-toc">
         <ol class="toc-list">
            {/* this is where toc list is rendered */}
         </ol>
    </div>
</aside>
```.

Should they be in the same div for it to work properly?

**Comment by hirusepalika** [comment]
I think I know why this is not updating anymore.
```
  // Fire scroll listener on hash change to trigger highlighting changes too.



  window.onhashchange = () => {


    _scrollListener()


  }

```

this part.
When we scroll we don't change the hash on the URL 😅 should that be part of the logic we need to implement?

**Comment by tscanlin** [comment]
Hmm, you shouldn't need to do anything special with the hashes or nesting the content differently. But that callback should also fire on scrollend. See [here](https://github.com/tscanlin/tocbot/blob/87a32ea9eeffae1a2da1525399e53bda71a2930c/src/js/index-esm.js#L112-L115)

```
// Fire scroll listener on hash change to trigger highlighting changes too.
  window.onhashchange = window.onscrollend = (e) => {
    _scrollListener(e)
  }
```

Maybe your code minification is not including the `window.onscrollend` part?

**Comment by tscanlin** [comment]
How is this implemented on your end? Is there a lot of custom code or how are you importing this? Seeing a minimal reproduction may be helpful.

It seems like the main part you are still missing is here: https://github.com/tscanlin/tocbot/blob/87a32ea9eeffae1a2da1525399e53bda71a2930c/src/js/build-html.js#L212-L215
Specifically the `isPageBottomMode` part doesn't appear to be getting checked but maybe I'm missing it.

Hope that helps!

**Comment by hirusepalika** [comment]
> How is this implemented on your end? Is there a lot of custom code or how are you importing this? Seeing a minimal reproduction may be helpful.
> 
> It seems like the main part you are still missing is here:
> 
> [tocbot/src/js/build-html.js](https://github.com/tscanlin/tocbot/blob/87a32ea9eeffae1a2da1525399e53bda71a2930c/src/js/build-html.js#L212-L215)
> 
> Lines 212 to 215 in [87a32ea](/tscanlin/tocbot/commit/87a32ea9eeffae1a2da1525399e53bda71a2930c)
>  const isPageBottomMode = getIsPageBottomMode() 
>  if (clickedHref && isBottomMode) { 
>    activeId = clickedHref.replace("#", "") 
>  } else if (hashId && hashId !== topHeaderId && isPageBottomMode) { 
> 
> Specifically the `isPageBottomMode` part doesn't appear to be getting checked but maybe I'm missing it.
> 
> vs (minified):
> 
> ```
> const g = l
>           , _ = ((F = o == null ? void 0 : o.target) == null ? void 0 : F.getAttribute("href")) || null
>           , k = _ && _.charAt(0) === "#" ? se(_.replace("#", "")) : !1;
> ```
> 
> Hope that helps!


I think you are referring to tocbot.min.js. I don't see this line at all.
```
(()=>{"use strict";var e={d:(t,n)=>{for(var o in n)e.o(n,o)&&!e.o(t,o)&&Object.defineProperty(t,o,{enumerable:!0,get:n[o]})},o:(e,t)=>Object.prototype.hasOwnProperty.call(e,t),r:e=>{"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})}},t={};function n(e){const t=[].forEach,n=[].some,o="undefined"!=typeof window&&document.body,l=" ";let r,s=!0;function i(n,o){const r=o.appendChild(function(n){const o=document.createElement("li"),r=document.createElement("a");return e.listItemClass&&o.setAttribute("class",e.listItemClass),e.onClick&&(r.onclick=e.onClick),e.includeTitleTags&&r.setAttribute("title",n.textContent),e.includeHtml&&n.childNodes.length?t.call(n.childNodes,(e=>{r.appendChild(e.cloneNode(!0))})):r.textContent=n.textContent,r.setAttribute("href",`${e.basePath}#${n.id}`),r.setAttribute("class",`${e.linkClass+l}node-name--${n.nodeName}${l}${e.extraLinkClasses}`),o.appendChild(r),o}(n));if(n.children.length){const e=c(n.isCollapsed);n.children.forEach((t=>{i(t,e)})),r.appendChild(e)}}function c(t){const n=e.orderedList?"ol":"ul",o=document.createElement(n);let r=e.listClass+l+e.extraListClasses;return t&&(r=r+l+e.collapsibleClass,r=r+l+e.isCollapsedClass),o.setAttribute("class",r),o}function a(t){let n=0;return null!==t&&(n=t.offsetTop,e.hasInnerContainers&&(n+=a(t.offsetParent))),n}function d(e,t){return e&&e.className!==t&&(e.className=t),e}function u(t){return t&&-1!==t.className.indexOf(e.collapsibleClass)&&-1!==t.className.indexOf(e.isCollapsedClass)?(d(t,t.className.replace(l+e.isCollapsedClass,"")),u(t.parentNode.parentNode)):t}function f(){const t=m(),n=t.scrollHeight>t.clientHeight,o=h()+t.clientHeight>t.offsetHeight-e.bottomModeThreshold;return n&&o}function m(){let t;return t=e.scrollContainer&&document.querySelector(e.scrollContainer)?document.querySelector(e.scrollContainer):document.documentElement||o,t}function h(){const e=m();return e?.scrollTop||0}function p(t,o=h()){let l;return n.call(t,((n,r)=>a(n)>o+e.headingsOffset+10?(l=t[0===r?r:r-1],!0):r===t.length-1?(l=t[t.length-1],!0):void 0)),l}return{enableTocAnimation:function(){s=!0},disableTocAnimation:function(t){const n=t.target||t.srcElement;"string"==typeof n.className&&-1!==n.className.indexOf(e.linkClass)&&(s=!1)},render:function(e,t){const n=c(!1);if(t.forEach((e=>{i(e,n)})),r=e||r,null!==r)return r.firstChild&&r.removeChild(r.firstChild),0===t.length?r:r.appendChild(n)},updateToc:function(n,o){e.positionFixedSelector&&function(){const t=h(),n=document.querySelector(e.positionFixedSelector);"auto"===e.fixedSidebarOffset&&(e.fixedSidebarOffset=r.offsetTop),t>e.fixedSidebarOffset?-1===n.className.indexOf(e.positionFixedClass)&&(n.className+=l+e.positionFixedClass):n.className=n.className.replace(l+e.positionFixedClass,"")}();const i=n,c=o?.target?.getAttribute?o?.target?.getAttribute("href"):null,a=!(!c||"#"!==c.charAt(0))&&function(t){const n=m(),o=n?.querySelector(`#${t}`);return o.offsetTop>n.offsetHeight-1.4*n.clientHeight-e.bottomModeThreshold}(c.replace("#",""));if((s||a)&&r&&i.length>0){const n=p(i),o=r.querySelector(`.${e.activeLinkClass}`),s=n.id.replace(/([ #;&,.+*~':"!^$[\]()=>|/\\@])/g,"\\$1"),m=window.location.hash.replace("#","");let h=s;const g=f();c&&a?h=c.replace("#",""):m&&m!==s&&g&&(h=m);const C=r.querySelector(`.${e.linkClass}[href="${e.basePath}#${h}"]`);if(o===C)return;const b=r.querySelectorAll(`.${e.linkClass}`);t.call(b,(t=>{d(t,t.className.replace(l+e.activeLinkClass,""))}));const S=r.querySelectorAll(`.${e.listItemClass}`);t.call(S,(t=>{d(t,t.className.replace(l+e.activeListItemClass,""))})),C&&-1===C.className.indexOf(e.activeLinkClass)&&(C.className+=l+e.activeLinkClass);const y=C?.parentNode;y&&-1===y.className.indexOf(e.activeListItemClass)&&(y.className+=l+e.activeListItemClass);const v=r.querySelectorAll(`.${e.listClass}.${e.collapsibleClass}`);t.call(v,(t=>{-1===t.className.indexOf(e.isCollapsedClass)&&(t.className+=l+e.isCollapsedClass)})),C?.nextSibling&&-1!==C.nextSibling.className.indexOf(e.isCollapsedClass)&&d(C.nextSibling,C.nextSibling.className.replace(l+e.isCollapsedClass,"")),u(C?.parentNode.parentNode)}},getCurrentlyHighlighting:function(){return s},getTopHeader:p,getScrollTop:h,updateUrlHashForHeader:function(e){const t=h(),n=p(e,t),o=f();if(n&&!(t<5)||o){if(n&&!o){const e=`#${n.id}`;window.location.hash!==e&&window.history.pushState(null,null,e)}}else"#"!==window.location.hash&&""!==window.location.hash&&window.history.pushState(null,null,"#")}}}e.r(t),e.d(t,{_buildHtml:()=>r,_headingsArray:()=>i,_options:()=>d,_parseContent:()=>s,_scrollListener:()=>c,default:()=>C,destroy:()=>f,init:()=>u,refresh:()=>m});const o={tocSelector:".js-toc",tocElement:null,contentSelector:".js-toc-content",contentElement:null,headingSelector:"h1, h2, h3",ignoreSelector:".js-toc-ignore",hasInnerContainers:!1,linkClass:"toc-link",extraLinkClasses:"",activeLinkClass:"is-active-link",listClass:"toc-list",extraListClasses:"",isCollapsedClass:"is-collapsed",collapsibleClass:"is-collapsible",listItemClass:"toc-list-item",activeListItemClass:"is-active-li",collapseDepth:0,scrollSmooth:!0,scrollSmoothDuration:420,scrollSmoothOffset:0,scrollEndCallback:function(e){},headingsOffset:1,throttleTimeout:50,positionFixedSelector:null,positionFixedClass:"is-position-fixed",fixedSidebarOffset:"auto",includeHtml:!1,includeTitleTags:!1,onClick:function(e){},orderedList:!0,scrollContainer:null,skipRendering:!1,headingLabelCallback:!1,ignoreHiddenElements:!1,headingObjectCallback:null,basePath:"",disableTocScrollSync:!1,tocScrollingWrapper:null,tocScrollOffset:30,enableUrlHashUpdateOnScroll:!1,bottomModeThreshold:30};function l(e){var t=e.duration,n=e.offset;if("undefined"!=typeof window&&"undefined"!=typeof location){var o=location.hash?l(location.href):location.href;document.body.addEventListener("click",(function(r){var s;"a"!==(s=r.target).tagName.toLowerCase()||!(s.hash.length>0||"#"===s.href.charAt(s.href.length-1))||l(s.href)!==o&&l(s.href)+"#"!==o||r.target.className.indexOf("no-smooth-scroll")>-1||"#"===r.target.href.charAt(r.target.href.length-2)&&"!"===r.target.href.charAt(r.target.href.length-1)||-1===r.target.className.indexOf(e.linkClass)||function(e,t){var n,o,l=window.pageYOffset,r={duration:t.duration,offset:t.offset||0,callback:t.callback,easing:t.easing||function(e,t,n,o){return(e/=o/2)<1?n/2*e*e+t:-n/2*(--e*(e-2)-1)+t}},s=document.querySelector('[id="'+decodeURI(e).split("#").join("")+'"]')||document.querySelector('[id="'+e.split("#").join("")+'"]'),i="string"==typeof e?r.offset+(e?s&&s.getBoundingClientRect().top||0:-(document.documentElement.scrollTop||document.body.scrollTop)):e,c="function"==typeof r.duration?r.duration(i):r.duration;function a(e){o=e-n,window.scrollTo(0,r.easing(o,l,i,c)),o<c?requestAnimationFrame(a):(window.scrollTo(0,l+i),"function"==typeof r.callback&&r.callback())}requestAnimationFrame((function(e){n=e,a(e)}))}(r.target.hash,{duration:t,offset:n,callback:function(){var e,t;e=r.target.hash,(t=document.getElementById(e.substring(1)))&&(/^(?:a|select|input|button|textarea)$/i.test(t.tagName)||(t.tabIndex=-1),t.focus())}})}),!1)}function l(e){return e.slice(0,e.lastIndexOf("#"))}}let r,s,i,c,a,d={};function u(e){let t=!1;d=function(...e){const t={};for(let n=0;n<e.length;n++){const o=e[n];for(const e in o)h.call(o,e)&&(t[e]=o[e])}return t}(o,e||{}),d.scrollSmooth&&(d.duration=d.scrollSmoothDuration,d.offset=d.scrollSmoothOffset,l(d)),r=n(d),s=function(e){const t=[].reduce;function n(e){return e[e.length-1]}function o(e){return+e.nodeName.toUpperCase().replace("H","")}function l(t){if(!function(e){try{return e instanceof window.HTMLElement||e instanceof window.parent.HTMLElement}catch(t){return e instanceof window.HTMLElement}}(t))return t;if(e.ignoreHiddenElements&&(!t.offsetHeight||!t.offsetParent))return null;const n=t.getAttribute("data-heading-label")||(e.headingLabelCallback?String(e.headingLabelCallback(t.innerText)):(t.innerText||t.textContent).trim()),l={id:t.id,children:[],nodeName:t.nodeName,headingLevel:o(t),textContent:n};return e.includeHtml&&(l.childNodes=t.childNodes),e.headingObjectCallback?e.headingObjectCallback(l,t):l}return{nestHeadingsArray:function(o){return t.call(o,(function(t,o){const r=l(o);return r&&function(t,o){const r=l(t),s=r.headingLevel;let i=o,c=n(i),a=s-(c?c.headingLevel:0);for(;a>0&&(c=n(i),!c||s!==c.headingLevel);)c&&void 0!==c.children&&(i=c.children),a--;s>=e.collapseDepth&&(r.isCollapsed=!0),i.push(r)}(r,t.nest),t}),{nest:[]})},selectHeadings:function(t,n){let o=n;e.ignoreSelector&&(o=n.split(",").map((function(t){return`${t.trim()}:not(${e.ignoreSelector})`})));try{return t.querySelectorAll(o)}catch(e){return console.warn(`Headers not found with selector: ${o}`),null}}}}(d),f();const u=function(e){try{return e.contentElement||document.querySelector(e.contentSelector)}catch(t){return console.warn(`Contents element not found: ${e.contentSelector}`),null}}(d);if(null===u)return;const m=g(d);if(null===m)return;if(i=s.selectHeadings(u,d.headingSelector),null===i)return;const C=s.nestHeadingsArray(i).nest;if(d.skipRendering)return this;r.render(m,C);let b=!1;c=p((e=>{r.updateToc(i,e),!d.disableTocScrollSync&&!b&&function(e){const t=e.tocScrollingWrapper||e.tocElement||document.querySelector(e.tocSelector);if(t&&t.scrollHeight>t.clientHeight){const n=t.querySelector(`.${e.activeListItemClass}`);if(n){const o=n.offsetTop-e.tocScrollOffset;t.scrollTop=o>0?o:0}}}(d),d.enableUrlHashUpdateOnScroll&&t&&r.getCurrentlyHighlighting()&&r.updateUrlHashForHeader(i);const n=e?.target?.scrollingElement&&0===e.target.scrollingElement.scrollTop;(e&&(0===e.eventPhase||null===e.currentTarget)||n)&&(r.updateToc(i),d.scrollEndCallback&&d.scrollEndCallback(e))}),d.throttleTimeout),t||(c(),t=!0),window.onhashchange=window.onscrollend=e=>{c(e)},d.scrollContainer&&document.querySelector(d.scrollContainer)?(document.querySelector(d.scrollContainer).addEventListener("scroll",c,!1),document.querySelector(d.scrollContainer).addEventListener("resize",c,!1)):(document.addEventListener("scroll",c,!1),document.addEventListener("resize",c,!1));let S=null;a=p((e=>{b=!0,d.scrollSmooth&&r.disableTocAnimation(e),r.updateToc(i,e),S&&clearTimeout(S),S=setTimeout((()=>{r.enableTocAnimation()}),d.scrollSmoothDuration),setTimeout((()=>{b=!1}),d.scrollSmoothDuration+100)}),d.throttleTimeout),d.scrollContainer&&document.querySelector(d.scrollContainer)?document.querySelector(d.scrollContainer).addEventListener("click",a,!1):document.addEventListener("click",a,!1)}function f(){const e=g(d);null!==e&&(d.skipRendering||e&&(e.innerHTML=""),d.scrollContainer&&document.querySelector(d.scrollContainer)?(document.querySelector(d.scrollContainer).removeEventListener("scroll",c,!1),document.querySelector(d.scrollContainer).removeEventListener("resize",c,!1),r&&document.querySelector(d.scrollContainer).removeEventListener("click",a,!1)):(document.removeEventListener("scroll",c,!1),document.removeEventListener("resize",c,!1),r&&document.removeEventListener("click",a,!1)))}function m(e){f(),u(e||d)}const h=Object.prototype.hasOwnProperty;function p(e,t,n){let o,l;return t||(t=250),function(...r){const s=n||this,i=+new Date;o&&i<o+t?(clearTimeout(l),l=setTimeout((()=>{o=i,e.apply(s,r)}),t)):(o=i,e.apply(s,r))}}function g(e){try{return e.tocElement||document.querySelector(e.tocSelector)}catch(t){return console.warn(`TOC element not found: ${e.tocSelector}`),null}}const C={_options:d,_buildHtml:r,_parseContent:s,init:u,destroy:f,refresh:m};var b,S;b="undefined"!=typeof global?global:window||global,S=function(e){const n=!!(e&&e.document&&e.document.querySelector&&e.addEventListener);if("undefined"!=typeof window||n)return e.tocbot=t,t},"function"==typeof define&&define.amd?define([],S(b)):"object"==typeof exports?module.exports=S(b):b.tocbot=S(b)})();
```
I do see this logic though in `build-html.js` in node_modules/../tocbot.

**Comment by hirusepalika** [comment]
@tscanlin I just found the issue, this fixed height messes up the highlighting 😅.
When I got rid of it, it works as expected!!!

<img width="246" alt="Image" src="https://github.com/user-attachments/assets/335e2290-395b-40b3-b729-ae88ad1a624d" />

`template-single` contains both content and toc sections.

This fixes the issue! No change needed on tocbot! Thank you for the fast responses!!

**Comment by tscanlin** [comment]
You are welcome! Glad to hear you found the cause of the issue!

**Comment by hirusepalika** [comment]
> You are welcome! Glad to hear you found the cause of the issue!

Sorry one last thing @tscanlin ! So one weird thing, when I scroll all the way down, the highlighter resets to the anchor that was clicked last. Is this a known thing? I tried forcing the highlight to stay on the last link in TOC if I am at the end of the page HOWEVER after a couple of seconds it resets to the last clicked link.

Any idea?

**Comment by tscanlin** [comment]
Hey, thanks for the heads up about this! This PR should fix that issue:
https://github.com/tscanlin/tocbot/pull/379

**Comment by hirusepalika** [comment]
> Hey, thanks for the heads up about this! This PR should fix that issue: [#379](https://github.com/tscanlin/tocbot/pull/379)

Awesome! Thank you 🙏 Closing this issue!

**Comment by tscanlin** [comment]
This is released now in: `tocbot@4.35.2`

**Comment by dingshaohua-com** [comment]
this can resolve myqs
